import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next-Hero",
  description: "Generated by next hero",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-2">
      <body className={inter.className}>
        <Navbar></Navbar>
        <div>
        {children}
        </div>
        </body>
    </html>
  );
}
